# Generated by Django 4.2.20 on 2025-04-19 12:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('poster', models.ImageField(upload_to='posters/')),
                ('category', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=256)),
                ('price', models.IntegerField()),
                ('trailer', models.URLField()),
                ('status', models.CharField(choices=[('showing', 'Now Showing'), ('upcoming', 'Upcoming Releases')], max_length=10)),
                ('release_date', models.DateField()),
                ('language', models.CharField(default='English', max_length=256)),
                ('duration', models.DurationField(default=datetime.timedelta(seconds=7200))),
            ],
        ),
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('category', models.CharField(max_length=256)),
                ('image', models.ImageField(upload_to='offers/')),
                ('description', models.CharField(max_length=256)),
                ('offer_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
